// first item will contain backpack data here
export const data = [
  {
    offerName: "",
    logoName: "powered.png",
    title: {
      text: "YOUR <br/>BACKPACK",
      color: "#0F1B33",
    },
    subTitle: {
      text: null,
      color: null,
    },
    imageName: "bag.webp",
    backgroundColor: "#B7C8E7",
    gradientColor: "#FBFCFF",
    itemIcon: "bag.png",
    button: {
      title: "SWIPE TO OPEN",
      backgroundColor: null,
      titleColor: null,
      url: null,
      isDeepLink: false,
    },
  },
  {
    offerName: "Chegg Study",
    logoName: "chegg_logo.png",
    title: {
      text: "24/7 study help",
      color: "#0F1B33",
    },
    subTitle: {
      text: "Plus perks from DoorDash, <br />Calm, and more",
      color: "#0F1B33",
    },
    imageName: "books.webp",
    backgroundColor: "#F6C67E",
    gradientColor: "#FAEDE1",
    itemIcon: "book_icon.png",
    button: {
      title: "HOOK ME UP",
      backgroundColor: "#0F1B33",
      titleColor: "#FFF",
      url: "https://www.chegg.com/study?utm_source=ZeeMee&utm_medium=cpc&utm_campaign=acceptance2023",
      isDeepLink: false,
    },
  },
  {
    offerName: "ZeeMee Scholarship",
    logoName: "zeemee_logo.png",
    title: {
      text: "$1,000 is a lot <br />of change",
      color: "#0F1B33",
    },
    subTitle: {
      text: "Apply for exclusive scholarships <br />every month",
      color: "#0F1B33",
    },
    imageName: "piggy_bank.webp",
    backgroundColor: "#A0D2E2",
    gradientColor: "#F7FAFB",
    itemIcon: "scholarship_icon.png",
    button: {
      title: "KA-CHING",
      backgroundColor: "#0F1B33",
      titleColor: "#FFF",
      url: "https://www.zeemee.com/contests/standard/32b7d589-faaf-4d60-a3a2-e09de282d68a/submission",
      // url: "https://www.zaptack.com/contests/standard/5506b64c-175d-4862-881e-8f0a8f9f5302/submission",
      isDeepLink: true,
    },
  },
  {
    offerName: "ZeeMee Scholarship",
    logoName: "atlantic_records_logo.png",
    title: {
      text: "Win Ed Sheeran's <br />guitar",
      color: "#FFF",
    },
    subTitle: {
      text: "One lucky fan will win a guitar played <br />by Ed Sheeran in concert",
      color: "#FFF",
    },
    imageName: "guitar_shadow.webp",
    backgroundColor: "#151616",
    gradientColor: "#6A6C6D",
    itemIcon: "music_note.png",
    button: {
      title: "ADMIT ONE",
      backgroundColor: "#FFF",
      titleColor: "#0F1B33",
      url: null,
      isDeepLink: false,
    },
  },
  {
    offerName: "Atlantic Records Daily Giveaway",
    logoName: "atlantic_records_logo.png",
    title: {
      text: "25 weekdays of hot <br />giveaways",
      color: "#0F1B33",
    },
    subTitle: {
      text: "Enter every 24 hours for free giveaways <br />from your favorite artists and brands",
      color: "#0F1B33",
    },
    imageName: "atlantic_shadow.webp",
    backgroundColor: "#D7D7D7",
    gradientColor: "#FEFDFD",
    itemIcon: "tickets_icon.png",
    button: {
      title: "I NEED THIS",
      backgroundColor: "#0F1B33",
      titleColor: "#FFF",
      url: "https://AtlanticHoliday.lnk.to/ZeeMee!App",
      isDeepLink: false,
    },
  },
  {
    offerName: "ZeeMee Airpods Pro Giveaway",
    logoName: "zeemee_logo.png",
    title: {
      text: "Listen up",
      color: "#0F1B33",
    },
    subTitle: {
      text: "Enter once a day to win this month’s <br />AirPods Pro giveaway",
      color: "#0F1B33",
    },
    imageName: "airpods_shadow.webp",
    backgroundColor: "#8CD9C7",
    gradientColor: "#EAFAF6",
    itemIcon: "headphone_icon.png",
    button: {
      title: "I WANT IT",
      backgroundColor: "#0F1B33",
      titleColor: "#FFF",
      url: "https://www.zeemee.com/contests/standard/e76719fa-f944-4bbf-99ad-3fa36ce19e23/submission",
      // url: "https://www.zaptack.com/contests/standard/6ddac548-3680-40eb-9614-296fabff3c53/submission",
      isDeepLink: true,
    },
  },
  {
    offerName: "ZeeMee Instax Mini Giveaway",
    logoName: "zeemee_logo_transparent.png",
    title: {
      text: "Capture the moment",
      color: "#FFF",
    },
    subTitle: {
      text: "Enter once a day to win this month’s <br />Instax giveaway",
      color: "#FFF",
    },
    imageName: "instax_shadow.webp",
    backgroundColor: "#CF361F",
    gradientColor: "#FDA68B",
    itemIcon: "camera_icon.png",
    button: {
      title: "GIMME",
      backgroundColor: "#FFF",
      titleColor: "#0F1B33",
      url: "https://www.zeemee.com/contests/standard/15f2463c-5980-4c07-b854-5a0a4b71f210/submission",
      // url: "https://www.zaptack.com/contests/standard/e731079a-ece2-4a39-a559-d5b02c30bf08/submission",
      isDeepLink: true,
    },
  },
];
