import { colors } from "./theme";

export const SWIPER_DATA = [
  {
    logoName: "sponsored.png",
    title: "",
    subTitle: "",
    imgName: "bag.png",
    color: colors.lavender,
    buttonTitle: "Swipe for deals",
    iconName: "bag.png",
    darkTheme: false,
  },
  {
    logoName: "chegg_logo.png",
    title: "Score extras for school & life",
    subTitle: "Get free perks from DoorDash, Calm, and Prezi with Chegg Study",
    imgName: "books.png",
    color: colors.golden,
    buttonTitle: "HIT THE BOOKS",
    iconName: "book_icon.png",
    darkTheme: false,
  },
  {
    logoName: "zeemee_logo.png",
    title: "$1,000 a month is a lot of change",
    subTitle: "Apply to exclusive scholarships just for the Zeemee community",
    imgName: "piggy_bank.png",
    color: colors.lightBlue,
    buttonTitle: "KA-Ching",
    iconName: "scholarship_icon.png",
    darkTheme: false,
  },
  {
    logoName: "zeemee_logo.png",
    title: "Essential gear for undergrads",
    subTitle: "Enter once a day to win this month’s AirPod giveaway",
    imgName: "airpods.png",
    color: colors.lightCyan,
    buttonTitle: "WANT",
    iconName: "headphone_icon.png",
    darkTheme: false,
  },
  {
    logoName: "zeemee_logo_transparent.png",
    title: "Did somebody say live music?",
    subTitle: "Enter to win tickets to an Ed Sheeran concert",
    imgName: "basket_ball.png",
    color: colors.darkGrey,
    buttonTitle: "Admit One",
    iconName: "tickets_icon.png",
    darkTheme: true,
  },
  {
    logoName: "nba_logo.png",
    title: "Follow your team all season",
    subTitle: "Get 40% off NBA League Pass",
    imgName: "basket_ball.png",
    color: colors.vbBlue,
    buttonTitle: "Swish",
    iconName: "basketball_icon.png",
    darkTheme: true,
  },
  {
    logoName: "nba_logo.png",
    title: "Follow your team all season",
    subTitle: "Get 40% off NBA League Pass",
    imgName: "basket_ball.png",
    color: colors.vbBlue,
    buttonTitle: "Swish",
    iconName: "basketball_icon.png",
    darkTheme: true,
  },
];
